### ISSUE TITLE
Not Working In IOS

### ISSUE THREAD

**Issue by codehack26** [talsec/Free-RASP-Cordova#28] opened 2024-05-09 07:15 UTC
**Describe the bug**
App crashes with an exception in TalsecPlugin

**To Reproduce**
If applicable, steps to reproduce the behavior.
Step 1:  Installed the cordova plugin add cordova-plugin-add-swift-support --save
Step 2: Installed the cordova plugin add cordova-talsec-plugin-freerasp
Step 3: Configuration Code added in JS file
Step 4: Run the Real device with simulator

**Expected behavior**
App should not crash & detect type of Security Threat

**Screenshots**

<img width="1440" alt="Screenshot 2024-05-09 at 12 40 03 PM" src="https://github.com/talsec/Free-RASP-Cordova/assets/59353691/22d88e20-7c48-4ece-86f2-c42e8b647544">

**Please complete the following information:**
 - Device: Iphone 13 pro max
 - OS version: 17.4.1
 - Version of freeRASP: 6.1.1

**Additional context**

**Comment by tompsota** [comment] 2024-05-09 10:06
Hi @codehack26,

did this happen  on fresh install of freeRASP, or are you updating from a previous version?

Best,
Tomas from Talsec

**Comment by codehack26** [comment] 2024-05-14 09:26
@tompsota Were you able to reproduce the issues.?

**Comment by tompsota** [comment] 2024-05-14 14:25
Hi @codehack26,

No, I wasn't able to reproduce. 

What version of 'cordova-ios' and 'cordova-plugin-add-swift-support' are you using?

Additionally, in the following gist is index.js of a demo app I used for testing. It should start freeRASP and log any detected incidents. https://gist.github.com/tompsota/f2a9e70ac6497cdb0ffe10dced16c80b . Can you try it on the blank project to see if the issue is still there?

**Comment by codehack26** [comment] 2024-05-15 06:36
@tompsota Please find the details
cordova-ios: 6.3.0 
cordova-plugin-add-swift-support : 2.0.2

Can you try it on the blank project to see if the issue is still there?
Same error in blank project. Seems like some issue with plugin

**Comment by tompsota** [comment] 2024-05-15 07:18
Hello @codehack26,

I was finally able to reproduce the bug. It is caused by `cordova-ios` plugin. More specifically, just by some versions of it. I'll try to fix it.

However, newer versions of the ios plugin do not throw the error, so maybe consider to bump the `cordova-ios`. I'm not sure what is the least version that fixes the problem, but I can say that with `"cordova-ios": "^7.1.0"`, the project builds successfully.

Cheers,

Tomas from Talsec

**Comment by codehack26** [comment] 2024-05-15 10:43
@tompsota Thanks for the update. Awaiting for the fix for lower version of cordova-ios

**Comment by tompsota** [comment] 2024-05-16 08:33
Issue should be resolved in v6.1.2

@codehack26, please try to update the freerasp plugin

Best,
Tomas from Talsec

**Comment by codehack26** [comment] 2024-05-16 08:39
@tompsota Appreciate your quick response. We will let you know if we face any issue.

**Comment by codehack26** [comment] 2024-05-16 09:58
@codehack26 Still we are facing same issue. Screenshot attached for your reference. We have update the TalsecPlugin.swift t manually as of now. I have not see any other change with the latest commit 
<img width="1331" alt="image" src="https://github.com/talsec/Free-RASP-Cordova/assets/59353691/b10d92bb-82f0-42b1-b456-ca5d9517cad9">

**Comment by tompsota** [comment] 2024-05-16 10:25
@codehack26 Allright. Let's try different approach.

Can you try to replace the SecurityThreat extension with following code?

https://gist.github.com/tompsota/737ffb2a8599641644f4fd72de38af64

Let me know if this helped, and I'll create a new release then.

**Comment by codehack26** [comment] 2024-05-17 13:09
@tompsota Error is resolved. App is not crashing now. Exploring the configuration(debug, jailbreak etc) available on IOS

**Closed** 2024-05-20 08:51 UTC
Labels: bug

**Comment by tompsota** [comment] 2024-05-22 11:28
Issue is resolved in v6.1.3.
